name: Build
on:
  push:
    branches-ignore: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}

      - run: npm ci

      - name: Build and export
        env:
          NEXT_PUBLIC_BASE_PATH: /racing-calendar
          F1_KEY: ${{ secrets.F1_KEY }}
          F2_KEY: ${{ secrets.F2_KEY }}
          F3_KEY: ${{ secrets.F3_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          npm run build
          npm run export