name: Build and deploy
on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * 1,4'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}

      - run: npm ci

      - name: Build and export
        env:
          NEXT_PUBLIC_BASE_PATH: /raceweek
          F1_KEY: ${{ secrets.F1_KEY }}
          F2_KEY: ${{ secrets.F2_KEY }}
          F3_KEY: ${{ secrets.F3_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          npm run scrape-events
          npm run build
          npm run export

      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: production-build
          path: out

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: production-build
          path: out

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out