name: CI
on:
  - pull_request
  - pull_request_target
jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]') ||
      (github.event_name != 'pull_request_target' && github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.sha || '' }}

      - uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}

      - run: npm ci

      - name: Build and export
        env:
          NEXT_PUBLIC_BASE_PATH: /raceweek
          F1_KEY: ${{ secrets.F1_KEY }}
          F2_KEY: ${{ secrets.F2_KEY }}
          F3_KEY: ${{ secrets.F3_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          npm run build
          npm run export